### PR TITLE
facial expression

### PR DESCRIPTION
**Pull request by Geta-meko**

### CODE REVIEW

**Comment by Dagiopia** [comment]
what's the point of being able to tell the naturalness of a person's face? 
We just need ratio facial features so that we don't have to set a static threshold for classifying a person's mouth or eyes are open/closed , wide/narrow... for example to tell when an eye is closed, one can just look at the difference between the upper and lower landmark points of the eye but that wouldn't work for two people with different eye sizes and that's where the need to also consider the width of the eye comes from... so that it is the compared to the width before saying it's open or not. 
are you planning on doing something like that?

**Comment by Geta-meko** [comment]
my idea is that once the camera sees a face it works the ratio of that
particular face and compares it with the one we gave him as natural face.
For example if the camera is given a smiley face it takes the ratio of the
upper and lower landmarks of the lip and verses the  upper landmark of lip
to the bottom of chin.
if the ratio is somewhat grater than to that of the natural face it will
understand the face is smiley. we can implement it using switch...
this was my plan

**Comment by Geta-meko** [comment]
by the way i used some landmarks from the 68 lms model. but i will edit it
as soon as u included those i suggested last week

**Comment by Dagiopia** [comment]
I couldn't train a new model this week... will send you a 42 points one today. Training will be done in a couple of hours.

**Pull request merged**
